### ISSUE TITLE
Access to repos from PRIDE Team at EBI

### ISSUE THREAD

**Issue by mbdebian** [spectra-cluster/clustering-file-reader#1]
Hi guys,
I'm working in PRIDE Team at the EBI, now on PRIDE Cluster.

I'm updating and extending code and dependencies in PRIDE Cluster and other libraries it depends on, one of them is clustering-file-reader.

I was wondering if I could be invited to this organisation so I can push changes into the repos.

Thanks,
Manuel

**Comment by ypriverol** [comment]
Done
